-- AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
-- Generated by database/schema_builder.py

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;

-- TABLE 1: screening_runs
CREATE TABLE IF NOT EXISTS screening_runs (
    run_id TEXT PRIMARY KEY,
    run_date TEXT NOT NULL,
    run_status TEXT NOT NULL DEFAULT 'RUNNING'
        CHECK (run_status IN ('RUNNING','COMPLETED','FAILED','ABORTED')),
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    universe_size INTEGER NOT NULL DEFAULT 200,
    passed_liquidity_count INTEGER DEFAULT 0,
    passed_volatility_count INTEGER DEFAULT 0,
    passed_events_count INTEGER DEFAULT 0,
    passed_regime_count INTEGER DEFAULT 0,
    watchlist_count INTEGER DEFAULT 0,
    config_snapshot_json TEXT NOT NULL,
    error_message TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_completed_run_per_date
    ON screening_runs(run_date) WHERE run_status = 'COMPLETED';

-- TABLE 2: weekly_watchlist
CREATE TABLE IF NOT EXISTS weekly_watchlist (
    watchlist_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    epic TEXT NOT NULL,
    sector TEXT NOT NULL,
    region TEXT NOT NULL CHECK (region IN ('US','EU')),
    assigned_engine TEXT NOT NULL CHECK (assigned_engine IN ('MEAN_REVERSION','BREAKOUT')),
    permitted_direction TEXT NOT NULL
        CHECK (permitted_direction IN ('LONG_ONLY','SHORT_ONLY','BOTH')),
    sunday_composite_rank INTEGER NOT NULL CHECK (sunday_composite_rank BETWEEN 1 AND 15),
    sunday_composite_score REAL NOT NULL,
    atr_pct_60d REAL NOT NULL,
    quarantined_until TEXT,
    quarantine_checked_at INTEGER,
    created_at INTEGER NOT NULL,
    superseded_at INTEGER,
    FOREIGN KEY (run_id) REFERENCES screening_runs(run_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_watchlist_lookup
    ON weekly_watchlist(assigned_engine, quarantined_until);

-- TABLE 3: daily_signals
CREATE TABLE IF NOT EXISTS daily_signals (
    signal_id TEXT PRIMARY KEY,
    watchlist_id TEXT NOT NULL,
    epic TEXT NOT NULL,
    engine TEXT NOT NULL CHECK (engine IN ('MEAN_REVERSION','BREAKOUT')),
    direction TEXT NOT NULL CHECK (direction IN ('BUY','SELL_SHORT')),
    signal_date TEXT NOT NULL,
    signal_close_price REAL NOT NULL,
    structural_stop_price REAL NOT NULL,
    target_price REAL,
    initial_rr_ratio REAL,
    executable_rr_ratio REAL,
    provisional_priority REAL NOT NULL,
    final_priority REAL,
    breakout_thrust_atr REAL,
    compression_spread_pct REAL,
    stop_distance_pct REAL NOT NULL,
    next_ex_div_pct_of_price REAL,
    signal_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (signal_status IN ('PENDING','PROMOTED','ABORTED','EXPIRED')),
    abort_reason TEXT CHECK (abort_reason IS NULL OR abort_reason IN ('TIMEOUT','EXPIRED_NO_ENTRY','TIER_1_GAP_BREACH','TIER_2_EXHAUSTION','SPREAD_GATE_EXCEEDED','DAILY_QUARANTINE','MARGIN_CEILING_EXCEEDED','CONCURRENT_DIRECTION_CAP','RR_BELOW_FLOOR','AMBIGUOUS_BROKER_MATCH','CIRCUIT_BREAKER','BROKER_REJECTED')),
    reclaim_deadline_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (watchlist_id) REFERENCES weekly_watchlist(watchlist_id) ON DELETE RESTRICT,
    CONSTRAINT chk_aborted_signal_has_reason
        CHECK (signal_status != 'ABORTED' OR abort_reason IS NOT NULL),
    CONSTRAINT chk_engine_signal_integrity CHECK (
        (engine = 'BREAKOUT'
            AND target_price IS NULL AND initial_rr_ratio IS NULL
            AND breakout_thrust_atr IS NOT NULL AND compression_spread_pct IS NOT NULL)
        OR
        (engine = 'MEAN_REVERSION'
            AND target_price IS NOT NULL AND initial_rr_ratio IS NOT NULL
            AND breakout_thrust_atr IS NULL AND compression_spread_pct IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_signals_pending
    ON daily_signals(signal_status, provisional_priority DESC);

-- TABLE 4: orders_and_positions
CREATE TABLE IF NOT EXISTS orders_and_positions (
    client_order_id TEXT PRIMARY KEY,
    signal_id TEXT UNIQUE,
    reconciled_from_order_id TEXT UNIQUE,
    deal_reference TEXT UNIQUE,
    deal_id TEXT UNIQUE,
    epic TEXT NOT NULL,
    sub_account TEXT NOT NULL CHECK (sub_account IN ('SUB_A_MR','SUB_B_BO')),
    direction TEXT NOT NULL CHECK (direction IN ('BUY','SELL_SHORT')),
    order_status TEXT NOT NULL DEFAULT 'QUEUED' CHECK (order_status IN ('QUEUED','WAITING_RECLAIM','SUBMITTING','SUBMITTED','OPEN','CLOSING','CLOSED','ABORTED','REJECTED','UNKNOWN')),
    abort_reason TEXT CHECK (abort_reason IS NULL OR abort_reason IN ('TIMEOUT','EXPIRED_NO_ENTRY','TIER_1_GAP_BREACH','TIER_2_EXHAUSTION','SPREAD_GATE_EXCEEDED','DAILY_QUARANTINE','MARGIN_CEILING_EXCEEDED','CONCURRENT_DIRECTION_CAP','RR_BELOW_FLOOR','AMBIGUOUS_BROKER_MATCH','CIRCUIT_BREAKER','BROKER_REJECTED')),
    close_reason TEXT CHECK (close_reason IS NULL OR close_reason IN ('STOP_BROKER','TARGET_BROKER','TRAILING_STOP','TIME_STOP','CIRCUIT_BREAKER','MANUAL','RECONCILIATION_FORCE')),
    planned_entry_price REAL NOT NULL,
    executable_entry_price REAL,
    actual_fill_price REAL,
    initial_stop_price REAL NOT NULL,
    current_stop_price REAL NOT NULL,
    broker_stop_price REAL,
    target_price REAL,
    trailing_high_watermark REAL,
    trailing_low_watermark REAL,
    stop_version INTEGER NOT NULL DEFAULT 1,
    planned_risk_r_usd REAL NOT NULL,
    allocated_units REAL NOT NULL,
    margin_used_usd REAL DEFAULT 0.0,
    realized_pnl_usd REAL DEFAULT 0.0,
    realized_pnl_r REAL DEFAULT 0.0,
    overnight_fees_paid_usd REAL DEFAULT 0.0,
    created_at INTEGER NOT NULL,
    opened_at INTEGER,
    closed_at INTEGER,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES daily_signals(signal_id) ON DELETE RESTRICT,
    FOREIGN KEY (reconciled_from_order_id)
        REFERENCES orders_and_positions(client_order_id) ON DELETE RESTRICT,
    CONSTRAINT chk_terminal_has_reason
        CHECK (order_status NOT IN ('ABORTED','REJECTED') OR abort_reason IS NOT NULL),
    CONSTRAINT chk_reconciled_link_valid CHECK (
        reconciled_from_order_id IS NULL
        OR (signal_id IS NULL AND order_status IN ('OPEN','CLOSING','CLOSED'))
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_one_active_per_epic
    ON orders_and_positions(epic)
    WHERE order_status IN ('QUEUED','WAITING_RECLAIM','SUBMITTING','SUBMITTED',
                           'OPEN','CLOSING','UNKNOWN');

CREATE TRIGGER IF NOT EXISTS trg_prevent_order_deletion
BEFORE DELETE ON orders_and_positions
BEGIN
    SELECT RAISE(ABORT, 'Financial records are immutable and cannot be deleted.');
END;

-- TABLE 5: epic_blocks
CREATE TABLE IF NOT EXISTS epic_blocks (
    block_id INTEGER PRIMARY KEY AUTOINCREMENT,
    epic TEXT NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('MANUAL_POSITION_EXISTS','AMBIGUOUS_MATCH','PERSISTENT_DESYNC')),
    blocked_at INTEGER NOT NULL,
    unblocked_at INTEGER,
    cleared_by TEXT,
    clear_note TEXT,
    CONSTRAINT chk_cleared_block_audit
        CHECK (unblocked_at IS NULL OR (cleared_by IS NOT NULL AND clear_note IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_one_active_block_per_epic
    ON epic_blocks(epic) WHERE unblocked_at IS NULL;

-- TABLE 6: system_audit_log
CREATE TABLE IF NOT EXISTS system_audit_log (
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp INTEGER NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('RECONCILIATION','CIRCUIT_BREAKER_TRIP','LATE_FILL_ADOPTED','AMBIGUOUS_ORPHAN_ALERT','DISCREPANCY_FOUND','STOP_MISMATCH','EPIC_BLOCKED','RECOVERY_ACTION','API_TIMEOUT')),
    broker_position_count INTEGER,
    local_open_position_count INTEGER,
    discrepancy_detected INTEGER NOT NULL DEFAULT 0 CHECK (discrepancy_detected IN (0,1)),
    daily_realized_r REAL,
    circuit_breaker_active INTEGER DEFAULT 0 CHECK (circuit_breaker_active IN (0,1)),
    details_json TEXT,
    client_order_id TEXT,
    FOREIGN KEY (client_order_id)
        REFERENCES orders_and_positions(client_order_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON system_audit_log(timestamp DESC);

-- TABLE 7: system_state
CREATE TABLE IF NOT EXISTS system_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at INTEGER NOT NULL
);

INSERT OR IGNORE INTO system_state (key, value, updated_at) VALUES
    ('circuit_breaker_active','0', CAST(strftime('%s','now') AS INTEGER) * 1000),
    ('active_screening_run_id','NONE', CAST(strftime('%s','now') AS INTEGER) * 1000),
    ('last_reconciliation_time','0', CAST(strftime('%s','now') AS INTEGER) * 1000);
