#!/usr/bin/env python3
from enum import StrEnum

class PermittedDirection(StrEnum):
    LONG_ONLY = "LONG_ONLY"
    SHORT_ONLY = "SHORT_ONLY"
    BOTH = "BOTH"

class TradeDirection(StrEnum):
    BUY = "BUY"
    SELL_SHORT = "SELL_SHORT"

class SignalStatus(StrEnum):
    PENDING = "PENDING"
    PROMOTED = "PROMOTED"
    ABORTED = "ABORTED"
    EXPIRED = "EXPIRED"

class OrderStatus(StrEnum):
    QUEUED = "QUEUED"
    WAITING_RECLAIM = "WAITING_RECLAIM"
    SUBMITTING = "SUBMITTING"
    SUBMITTED = "SUBMITTED"
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    ABORTED = "ABORTED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"

class AbortReason(StrEnum):
    TIMEOUT = "TIMEOUT"
    EXPIRED_NO_ENTRY = "EXPIRED_NO_ENTRY"
    TIER_1_GAP_BREACH = "TIER_1_GAP_BREACH"
    TIER_2_EXHAUSTION = "TIER_2_EXHAUSTION"
    SPREAD_GATE_EXCEEDED = "SPREAD_GATE_EXCEEDED"
    DAILY_QUARANTINE = "DAILY_QUARANTINE"
    MARGIN_CEILING_EXCEEDED = "MARGIN_CEILING_EXCEEDED"
    CONCURRENT_DIRECTION_CAP = "CONCURRENT_DIRECTION_CAP"
    RR_BELOW_FLOOR = "RR_BELOW_FLOOR"
    AMBIGUOUS_BROKER_MATCH = "AMBIGUOUS_BROKER_MATCH"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    BROKER_REJECTED = "BROKER_REJECTED"


class CloseReason(StrEnum):
    STOP_BROKER = "STOP_BROKER"
    TARGET_BROKER = "TARGET_BROKER"
    TRAILING_STOP = "TRAILING_STOP"
    TIME_STOP = "TIME_STOP"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    MANUAL = "MANUAL"
    RECONCILIATION_FORCE = "RECONCILIATION_FORCE"

class EngineType(StrEnum):
    MEAN_REVERSION = "MEAN_REVERSION"
    BREAKOUT = "BREAKOUT"


class SubAccount(StrEnum):
    SUB_A_MR = "SUB_A_MR"
    SUB_B_BO = "SUB_B_BO"


class AuditEventType(StrEnum):
    RECONCILIATION = "RECONCILIATION"
    CIRCUIT_BREAKER_TRIP = "CIRCUIT_BREAKER_TRIP"
    LATE_FILL_ADOPTED = "LATE_FILL_ADOPTED"
    AMBIGUOUS_ORPHAN_ALERT = "AMBIGUOUS_ORPHAN_ALERT"
    DISCREPANCY_FOUND = "DISCREPANCY_FOUND"
    STOP_MISMATCH = "STOP_MISMATCH"
    EPIC_BLOCKED = "EPIC_BLOCKED"
    RECOVERY_ACTION = "RECOVERY_ACTION"
    API_TIMEOUT = "API_TIMEOUT"


class BlockReason(StrEnum):
    MANUAL_POSITION_EXISTS = "MANUAL_POSITION_EXISTS"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    PERSISTENT_DESYNC = "PERSISTENT_DESYNC"