"""
config/universe.py
Master Spec V4.1 Section 8.1 - Fixed Master Candidate Universe.
Precision GICS Classified Multi-Exchange Equity Universe (5 Premier Bourses).
Total Verified Liquid Assets: 574.
"""

from typing import Dict, Any

MASTER_UNIVERSE: Dict[str, Dict[str, Any]] = {
    "8TRA": {"name": "Traton SE", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AAF": {"name": "Airtel Africa Plc", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "AAG": {"name": "Aumann", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AAL": {"name": "American Airlines Group Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "AALL": {"name": "Anglo American", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "AAPL": {"name": "Apple Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "ABF": {"name": "ABF", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "ABNB": {"name": "Airbnb Inc", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "ABND": {"name": "ABN AMRO Group", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "ABVXP": {"name": "Abivax SA", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "AC": {"name": "Accor", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "ACAP": {"name": "Credit Agricole", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "ACHR": {"name": "Archer Aviation Inc.", "sector": "Industrials", "region": "US", "currency": "USD"},
    "ACN": {"name": "Accenture", "sector": "Technology", "region": "US", "currency": "USD"},
    "AD": {"name": "Koninklijke Ahold Delhaize", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "ADBE": {"name": "Adobe Systems Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "ADPP": {"name": "Aeroports De Paris", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ADSGN": {"name": "Adidas", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "ADSK": {"name": "Autodesk", "sector": "Technology", "region": "US", "currency": "USD"},
    "ADV": {"name": "ADVA Optical Networking SE", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "ADYENA": {"name": "Adyen NV", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "AEGN": {"name": "Aegon", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "AEHR": {"name": "Aehr Test Systems", "sector": "Technology", "region": "US", "currency": "USD"},
    "AFP": {"name": "Air France", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AFRM": {"name": "Affirm Holdings Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "AFX": {"name": "Carl Zeiss Meditec", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "AG1": {"name": "AUTO1 Group SE", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "AIFR": {"name": "Air Liquide", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "AIRFR": {"name": "Airbus", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AIXA": {"name": "AIXTRON SE NA O.N.", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "AKAM": {"name": "Akamai", "sector": "Technology", "region": "US", "currency": "USD"},
    "AKZO": {"name": "Akzo Nobel", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "ALAB": {"name": "Astera Labs Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "ALHC": {"name": "Alignment Healthcare Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "ALLFG": {"name": "Allfunds Group plc", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "ALO": {"name": "Alstom", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ALVD": {"name": "Allianz", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "AMAT": {"name": "Applied", "sector": "Technology", "region": "US", "currency": "USD"},
    "AMC": {"name": "AMC Entertainment Holdings Inc", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "AMD": {"name": "Advanced Micro Devices Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "AMFR": {"name": "Dassault Aviat", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AMGNL": {"name": "AMG Advanced Metallurgical Group", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "AML": {"name": "Aston Martin", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "AMUN": {"name": "Amundi", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AMZN": {"name": "Amazon.com Inc", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "ANTO": {"name": "Antofagasta", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "APAM.AS": {"name": "Aperam S.A.", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "APH": {"name": "Amphenol Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "APP": {"name": "Applovin Corporation", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "ARDS": {"name": "Arcadis NV", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ARM": {"name": "ARM Holdings PLC", "sector": "Technology", "region": "US", "currency": "USD"},
    "ASMI": {"name": "ASM International NV", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "ASML": {"name": "ASML Holding NV - ADR", "sector": "Technology", "region": "US", "currency": "USD"},
    "ASMLNL": {"name": "ASML Holding NV - EUR", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "ASRNL": {"name": "ASR Nederland NV", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "ASTS": {"name": "AST SpaceMobile, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "ATOP": {"name": "Atos", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "ATYM": {"name": "Atalaya Mining PLC", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "AUR": {"name": "Aurora Innovation, Inc.", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "AUTO": {"name": "Autotrader Group Plc", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "AV.": {"name": "Aviva", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "AVGO": {"name": "Broadcom Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "AXB": {"name": "Axis Bank", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "AXONUS": {"name": "Axon Enterprise Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "AXP": {"name": "American Express", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "AXTI": {"name": "AXT Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "AYV": {"name": "Ayvens SA", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "AZNL": {"name": "AstraZeneca - GBP", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "BA": {"name": "Boeing Co", "sector": "Industrials", "region": "US", "currency": "USD"},
    "BA.": {"name": "BAE Systems plc", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "BABA": {"name": "Alibaba Group Holding Ltd - ADR", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "BABL": {"name": "Babcock", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "BAC": {"name": "Bank of America Corp", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "BALF": {"name": "Balfour Beatty", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "BAMN": {"name": "Koninklijke BAM", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "BARC": {"name": "Barclays", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "BASD": {"name": "Basf", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "BATS": {"name": "British American Tobacco - GBP", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "BAYN": {"name": "Bayer", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "BB": {"name": "BlackBerry Limited", "sector": "Technology", "region": "US", "currency": "USD"},
    "BBOX": {"name": "Tritax Big Box REIT", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "BE": {"name": "Bloom Energy Corporation", "sector": "Industrials", "region": "US", "currency": "USD"},
    "BEI": {"name": "Beiersdorf", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "BESI": {"name": "BE Semiconductor Industries", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "BGEO": {"name": "Lion Finance Group PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "BICP": {"name": "Societe BIC", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "BIDU": {"name": "Baidu Inc - ADR", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "BIM": {"name": "Biomerieux", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "BKG": {"name": "Berkeley Group Holdings PLC", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "BKNG": {"name": "Booking Holdings Inc.", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "BME": {"name": "B&M European Value Retail PLC", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "BMW": {"name": "BMW", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "BN": {"name": "Danone", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "BNP": {"name": "BNP Paribas", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "BNR": {"name": "Brenntag", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "BOL": {"name": "Bollore", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "BOSSDE": {"name": "Hugo Boss", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "BP.": {"name": "BP - GBP", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "BRBY": {"name": "Burberry", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "BRSC": {"name": "Blackrock Smaller Co", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "BRUN": {"name": "Brunel International", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "BT.A": {"name": "BT Group PLC", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "BTDR": {"name": "Bitdeer Technologies Group", "sector": "Technology", "region": "US", "currency": "USD"},
    "BTRW": {"name": "Barratt Redrow PLC", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "BVB": {"name": "Borussia Dortmund", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "BVI": {"name": "Bureau Veritas", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "BWY": {"name": "Bellway", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "BYG": {"name": "Big Yellow Group", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "BYND": {"name": "Beyond Meat Inc", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "CAPFR": {"name": "Capgemini", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "CARF": {"name": "Carrefour", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "CAT": {"name": "Caterpillar", "sector": "Industrials", "region": "US", "currency": "USD"},
    "CBK": {"name": "Commerzbank", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "CCC": {"name": "Computacenter", "sector": "Technology", "region": "EU", "currency": "GBP"},
    "CCH": {"name": "Coca Cola - GBP", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "CCL": {"name": "Carnival Corp Limited", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "CDIP": {"name": "Christian Dior", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "CELH": {"name": "Celsius", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "CGG": {"name": "Viridien", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "CHTR": {"name": "Charter Communications", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "CIFR": {"name": "Cipher Mining Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "CLARI": {"name": "Clariane SE", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "CLSK": {"name": "CleanSpark, Inc.", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "CLX": {"name": "Clorox", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "CMCSA": {"name": "Comcast A", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "CMG": {"name": "Chipotle", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "CNAL": {"name": "Centrica", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "CNE": {"name": "Capricorn Energy", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "COHR": {"name": "COHERENT CORP", "sector": "Technology", "region": "US", "currency": "USD"},
    "COIN": {"name": "Coinbase Global Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "COK": {"name": "Cancom", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "COND": {"name": "Continental", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "CORB": {"name": "Corbion", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "COST": {"name": "Costco Wholesale Corporation", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "COV": {"name": "Covivio", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "CPI": {"name": "Capita", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "CRDA": {"name": "Croda International plc", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "CRM": {"name": "Salesforce Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "CRW": {"name": "Craneware PLC", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "CRWD": {"name": "CrowdStrike Holdings Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "CSCO": {"name": "Cisco", "sector": "Technology", "region": "US", "currency": "USD"},
    "CSP": {"name": "Axa", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "CVX": {"name": "Chevron", "sector": "Energy", "region": "US", "currency": "USD"},
    "CWR": {"name": "Ceres Power Holdings PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "DATAGB": {"name": "GlobalData PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "DB1": {"name": "Deutsche Boerse", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "DBK": {"name": "Deutsche Bank", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "DBV": {"name": "DBV Technologies", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "DDOG": {"name": "Datadog Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "DEBS": {"name": "boohoo Group PLC", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "DELL": {"name": "Dell Technologies Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "DEQ": {"name": "Deutsche Euroshop", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "DGE": {"name": "Diageo - GBP", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "DGP": {"name": "Vinci", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "DHER": {"name": "Delivery Hero", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "DHL": {"name": "DHL AG", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "DIM": {"name": "Sartorius Stedim Biotech", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "DIS": {"name": "Walt Disney Co", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "DNLM": {"name": "Dunelm Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "DRW8": {"name": "DRAEGERWERK ST.A.O.N.", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "DRX": {"name": "Drax Group", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "DSY": {"name": "Dassault System", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "DTED": {"name": "Deutsche Telekom", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "DTG": {"name": "Daimler Truck Holding AG", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "DWNI": {"name": "Deutsche Wohnen", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "EDENFR": {"name": "Edenred", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "EDVGB": {"name": "Endeavour Mining plc", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "EEE": {"name": "Empire Metals Ltd", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "ELFR": {"name": "EssilorLuxottica", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "ELIOR": {"name": "Elior Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "ELIS": {"name": "Elis", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ELIX": {"name": "Elixirr International PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "EN": {"name": "Bouygues", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ENGI": {"name": "Engie", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "ENPH": {"name": "Enphase Energy, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "ENRUS": {"name": "Siemens Energy AG", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "ENT": {"name": "Entain", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "ENX": {"name": "Euronext", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "EO": {"name": "Faurecia", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "EOAN": {"name": "E.ON", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "EOSE": {"name": "Eos Energy Enterprises Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "ERA": {"name": "Eramet", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "ERFP": {"name": "Eurofins", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "ETL": {"name": "Eutelsat", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "EVD": {"name": "Cts Eventim", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "EVK": {"name": "Evonik", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "EVOKGB": {"name": "Evoke PLC", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "EVT": {"name": "Evotec SE", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "EXPN": {"name": "Experian", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "EZJGB": {"name": "EasyJet", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "F": {"name": "Ford Motor Co", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "FCEL": {"name": "FuelCell Energy, Inc.", "sector": "Industrials", "region": "US", "currency": "USD"},
    "FDJUPUP": {"name": "FDJ United ", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "FGR": {"name": "Eiffage", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "FLNC": {"name": "Fluence Energy, Inc.", "sector": "Utilities", "region": "US", "currency": "USD"},
    "FLOW.AS": {"name": "Flow Traders", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "FME": {"name": "Fresenius Medical Care", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "FNAC": {"name": "Fnac Darty", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "FNTN": {"name": "Freenet", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "FPE3": {"name": "Fuchs Se", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "FRA": {"name": "Fraport", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "FRE": {"name": "Fresenius SE & Co", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "FRES": {"name": "Fresnillo", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "FRP": {"name": "Valeo", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "FSLR": {"name": "First Solar Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "FSLY": {"name": "Fastly, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "FUGRC": {"name": "Fugro", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "G1A": {"name": "Gea Group", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "G24": {"name": "Scout24", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "GAW": {"name": "Games Workshop Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "GBFDE": {"name": "Bilfinger", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "GENG": {"name": "Genuit Group", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "GETFR": {"name": "Getlink", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "GFC": {"name": "Gecina Reit", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "GLE": {"name": "Societe Generale", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "GLEN": {"name": "Glencore PLC", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "GLJ": {"name": "Grenke", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "GLW": {"name": "Corning", "sector": "Technology", "region": "US", "currency": "USD"},
    "GME": {"name": "GameStop Corp", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "GNC": {"name": "Greencore Group", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "GNFTFR": {"name": "Genfit", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "GNSGB": {"name": "Genus", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "GOOG": {"name": "Alphabet Inc - C", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "GOOGL": {"name": "Alphabet Inc - A", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "GRAB": {"name": "Grab Holdings Limited", "sector": "Technology", "region": "US", "currency": "USD"},
    "GRG": {"name": "Greggs", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "GS": {"name": "Goldman Sachs", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "GSKL": {"name": "GSK PLC - GBP", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "GTTFR": {"name": "GTT", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "HBH": {"name": "Hornbach", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "HBR": {"name": "Harbour Energy plc", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "HCA": {"name": "HCA Healtcare Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "HEID": {"name": "Heidelbergcement", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "HEIJ": {"name": "Heijmans", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "HEIN": {"name": "Heineken N.V.", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "HEIO": {"name": "Heineken Holding N.V.", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "HEN3": {"name": "Henkel", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "HIMS": {"name": "Hims & Hers Health, Inc.", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "HLE": {"name": "Hella", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "HLMA": {"name": "Halma", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "HLN": {"name": "Haleon PLC", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "HO": {"name": "Thales", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "HOC": {"name": "Hochschild Mining", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "HOOD": {"name": "Robinhood Markets Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "HPE": {"name": "Hewlett Packard Enterprise", "sector": "Technology", "region": "US", "currency": "USD"},
    "HPOW": {"name": "H-Power PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "HSBA": {"name": "HSBC - GBP", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "HWDN": {"name": "Howden Joinery Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "IAG": {"name": "IAG - GBP", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "IBM": {"name": "IBM Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "IFX": {"name": "Infineon", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "III": {"name": "3i Group Plc", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "IMB": {"name": "Imperial", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "IMCD": {"name": "IMCD", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "INF": {"name": "Informa", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "INGA": {"name": "ING Groep", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "INS": {"name": "Instone Real Estate Group SE", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "INTC": {"name": "Intel Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "INTU": {"name": "Intuit", "sector": "Technology", "region": "US", "currency": "USD"},
    "INVP": {"name": "Investec", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "IONQ": {"name": "IonQ, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "IPN": {"name": "Ipsen", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "IPS": {"name": "Ipsos", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "IREN": {"name": "IREN Limited", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "ITM": {"name": "ITM Power", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "JD.": {"name": "JD Sports Fashion", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "JFJ": {"name": "JPMorgan Japanese Investment", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "JIGI": {"name": "JPMorgan India Growth & Income PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "JMAT": {"name": "Johnson Matthey", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "JNJ": {"name": "Johnson & Johnson", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "JPM": {"name": "JPMorgan Chase & Co", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "JSG": {"name": "Johnson Service Group PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "KBX": {"name": "Knorr-Bremse", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "KEEL": {"name": "Keel Infrastructure Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "KER": {"name": "Kering", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "KGC": {"name": "Kinross Gold", "sector": "Basic Materials", "region": "US", "currency": "USD"},
    "KGX": {"name": "KION", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "KIEGB": {"name": "Kier Group", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "KLRGB": {"name": "Keller Group", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "KO": {"name": "Coca-Cola Co", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "KPN": {"name": "Koninklijke KPN", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "KTOS": {"name": "Kratos Defense & Security Solutions Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "LANDL": {"name": "Land Securities", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "LCID": {"name": "Lucid Group, Inc.", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "LGEN": {"name": "Legal & General", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "LHA": {"name": "Lufthansa", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "LI": {"name": "Klepierre", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "LIAC": {"name": "Lithium Americas Corp", "sector": "Basic Materials", "region": "US", "currency": "USD"},
    "LIGHT": {"name": "Signify", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "LITE": {"name": "Lumentum", "sector": "Technology", "region": "US", "currency": "USD"},
    "LIUS": {"name": "Li Auto Inc - ADR", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "LKFTA": {"name": "Lakefront Biotherapeutics", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "LLOY": {"name": "Lloyds Banking Group PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "LLY": {"name": "Eli Lilly & Co", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "LMP": {"name": "Londonmetric Property", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "LPK": {"name": "LPKF LASER+ELECTRON.", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "LR": {"name": "Legrand", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "LSE": {"name": "LSE", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "LUCEL": {"name": "Luceco PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "LULU": {"name": "Lululemon Athletica", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "LXS": {"name": "Lanxess", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "M2Z": {"name": "Seeing Machines Ltd", "sector": "Technology", "region": "EU", "currency": "GBP"},
    "MA": {"name": "Mastercard Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "MARA": {"name": "Marathon Digital Holdings, Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "MBGN": {"name": "Mercedes Benz Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "MCD": {"name": "McDonald's", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "MCFR": {"name": "LVMH", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "MCG": {"name": "Mobico Group PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "MDM": {"name": "Maisons du Monde", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "MELI": {"name": "MercadoLibre", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "MERY": {"name": "Mercialys", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "META": {"name": "Meta Platforms Inc", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "MKS": {"name": "M&S", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "MLFR": {"name": "Michelin", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "MMB": {"name": "Lagardere", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "MMT": {"name": "Metropole Television", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "MNG": {"name": "M&G plc", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "MNKS": {"name": "Monks Investment", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "MP": {"name": "MP Materials Corp.", "sector": "Basic Materials", "region": "US", "currency": "USD"},
    "MPC": {"name": "Marathon Petroleum", "sector": "Energy", "region": "US", "currency": "USD"},
    "MRKD": {"name": "Merck - EUR", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "MRNA": {"name": "Moderna Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "MRO.L": {"name": "Melrose Industries PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "MRVL": {"name": "Marvell Technology Group Ltd.", "sector": "Technology", "region": "US", "currency": "USD"},
    "MSFT": {"name": "Microsoft Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "MSTR": {"name": "Strategy Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "MT": {"name": "ArcelorMittal", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "MTXDE": {"name": "MTU AERO ENGINES NA O.N.", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "MU": {"name": "Micron Technology Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "MUV2": {"name": "Munich Re", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "NA9": {"name": "Nagarro SE", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "NBIS": {"name": "Nebius Group NV", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "NCLH": {"name": "Norwegian Cruise Line Holdings Ltd", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "NDA": {"name": "Aurubis", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "NDAQ": {"name": "Nasdaq", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "NDX1": {"name": "Nordex", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "NEE": {"name": "Nextera Energy", "sector": "Utilities", "region": "US", "currency": "USD"},
    "NEM": {"name": "Newmont Goldcorp", "sector": "Basic Materials", "region": "US", "currency": "USD"},
    "NEMDE": {"name": "Nemetschek", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "NET": {"name": "Cloudflare", "sector": "Technology", "region": "US", "currency": "USD"},
    "NEXP": {"name": "Nexans", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "NG.": {"name": "National Grid", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "NIO": {"name": "NIO Inc - ADR", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "NK": {"name": "Imerys", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "NKE": {"name": "Nike Inc", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "NNNL": {"name": "NN Group", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "NOEJ": {"name": "Norma Group", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "NOK": {"name": "Nokia - USD", "sector": "Technology", "region": "US", "currency": "USD"},
    "NOW": {"name": "ServiceNow", "sector": "Technology", "region": "US", "currency": "USD"},
    "NU": {"name": "Nu Holdings Ltd.", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "NVAX": {"name": "Novavax Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "NVDA": {"name": "NVIDIA Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "NVO": {"name": "Novo Nordisk AS ADR", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "NVTS": {"name": "Navitas Semiconductor Corporation", "sector": "Technology", "region": "US", "currency": "USD"},
    "NWL": {"name": "Newell", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "NXI": {"name": "Nexity", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "NXPI": {"name": "NXP", "sector": "Technology", "region": "US", "currency": "USD"},
    "O": {"name": "Realty Income", "sector": "Real Estate", "region": "US", "currency": "USD"},
    "OCDO": {"name": "Ocado Group plc", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "OCGN": {"name": "Ocugen, Inc.", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "OKLO": {"name": "Oklo Inc", "sector": "Utilities", "region": "US", "currency": "USD"},
    "OKTA": {"name": "Okta", "sector": "Technology", "region": "US", "currency": "USD"},
    "OLMA": {"name": "Olema Pharmaceuticals, Inc.", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "ON": {"name": "ON Semiconductor", "sector": "Technology", "region": "US", "currency": "USD"},
    "ONT": {"name": "Oxford Nanopore Technologies PLC", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "OPEN": {"name": "Opendoor Technologies Inc", "sector": "Real Estate", "region": "US", "currency": "USD"},
    "OPM": {"name": "Opmobility", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "OR": {"name": "L'Oreal", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "ORAP": {"name": "Orange", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "ORCL": {"name": "Oracle", "sector": "Technology", "region": "US", "currency": "USD"},
    "OSCR": {"name": "Oscar Health, Inc.", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "OVH": {"name": "OVH Groupe S.A.", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "OXB": {"name": "Oxford BioMedica plc", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "OXY": {"name": "Occidental Petroleum Corp", "sector": "Energy", "region": "US", "currency": "USD"},
    "P911": {"name": "Porsche AG Vz", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "PAF": {"name": "Pan African Resources PLC", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "PAH3": {"name": "Porsche", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "PANW": {"name": "Palo Alto Networks", "sector": "Technology", "region": "US", "currency": "USD"},
    "PBB": {"name": "PBB", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "PENG": {"name": "Penguin Solutions Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "PEP": {"name": "Pepsi", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "PETSGBP": {"name": "PETS AT HOME GROUP PLC ORD 1P", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "PFE": {"name": "Pfizer Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "PHAR": {"name": "Pharming Group", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "PHGEUR": {"name": "Koninklijke Philips", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "PL": {"name": "Planet Labs PBC", "sector": "Industrials", "region": "US", "currency": "USD"},
    "PLTR": {"name": "Palantir Technologies Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "PLUG": {"name": "Plug Power Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "PLUSGBP": {"name": "Plus500", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "PNN": {"name": "Pennon", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "PRTC": {"name": "Puretech Health plc", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "PRUL": {"name": "Prudential", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "PRX": {"name": "Prosus NV", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "PSM": {"name": "PSM", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "PSX": {"name": "Phillips", "sector": "Energy", "region": "US", "currency": "USD"},
    "PTEC": {"name": "Playtech", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "PTNL": {"name": "PostNL", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "PUBP": {"name": "Publicis", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "PYPL": {"name": "PayPal Holdings Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "PZZA": {"name": "Papa John's International Inc", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "QBTS": {"name": "D-Wave Quantum Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "QCOM": {"name": "QUALCOMM Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "QIA0": {"name": "Qiagen", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "QLT": {"name": "Quilter", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "RAA": {"name": "Rational AG", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "RAND": {"name": "Randstad NV", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "RB.": {"name": "Reckitt Benckiser Group", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "RBLX": {"name": "Roblox Corp", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "RBSL": {"name": "NatWest Group PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "RCF": {"name": "Teleperformance", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "RCH": {"name": "REACH PLC", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "RCL": {"name": "Royal Caribbean Cruises Ltd", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "RDDT": {"name": "Reddit Inc", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "RDW": {"name": "Redwire Corp", "sector": "Industrials", "region": "US", "currency": "USD"},
    "REL": {"name": "Reed", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "RFP": {"name": "Eurazeo", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "RGTI": {"name": "Rigetti Computing, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "RHM": {"name": "Rheinmetall", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "RI": {"name": "Pernod Ricard", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "RIOGB": {"name": "Rio Tinto - GBP", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "RIOT": {"name": "Riot Blockchain, Inc.", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "RIVN": {"name": "Rivian Automotive Inc.", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "RKLB": {"name": "Rocket Lab USA Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "RMBS": {"name": "Rambus Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "RMS": {"name": "Hermes", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "RMV": {"name": "Rightmove", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "RNOFR": {"name": "Renault", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "RNWH": {"name": "Renew Holdings PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "RPI": {"name": "Raspberry PI Holdings PLC", "sector": "Technology", "region": "EU", "currency": "GBP"},
    "RR.": {"name": "Rolls-royce", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "RRTL": {"name": "RTL Group", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "RSW": {"name": "Renishaw", "sector": "Technology", "region": "EU", "currency": "GBP"},
    "RTO": {"name": "Rentokil Initial plc", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "RUI": {"name": "Rubis", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "RWE": {"name": "RWE", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "RXLFR": {"name": "Rexel", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "S92": {"name": "SMA Solar Technology AG", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "SAAGB": {"name": "M&C Saatchi PLC", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "SAF": {"name": "Safran", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SANFR": {"name": "Sanofi", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "SAPD": {"name": "SAP", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "SBMO": {"name": "SBM Offshore", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "SBRY": {"name": "Sainsbury", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "SBS": {"name": "Stratec SE", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "SCR": {"name": "Scor", "sector": "Financial Services", "region": "EU", "currency": "EUR"},
    "SDF": {"name": "K+S", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "SDLF": {"name": "Standard Life PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "SE": {"name": "Sea Limited", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "SEDG": {"name": "SolarEdge Technologies", "sector": "Technology", "region": "US", "currency": "USD"},
    "SEPL": {"name": "SEPLAT Energy PLC", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "SESG": {"name": "Ses Fdr", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "SFQ": {"name": "SAF-Holland SE", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "SGL": {"name": "Sgl Carbon", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "SGO": {"name": "Saint-Gobain", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SGRO": {"name": "SEGRO Plc", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "SHA": {"name": "Schaeffler", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "SHELA": {"name": "Shell - EUR", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "SHELGB": {"name": "Shell - GBP", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "SHL": {"name": "Siemens Healthineers AG", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "SHOP": {"name": "Shopify Inc (US)", "sector": "Technology", "region": "US", "currency": "USD"},
    "SIE": {"name": "Siemens", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SIFG": {"name": "Sif", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SIPFC": {"name": "Eurocommercial Properties", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "SIX2": {"name": "Sixt AG", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SK": {"name": "Seb", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "SLIGR": {"name": "Sligro Food Group", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "SMCI": {"name": "Super Micro Computer, Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "SMINGB": {"name": "Smiths", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "SMR": {"name": "NuScale Power Corporation", "sector": "Industrials", "region": "US", "currency": "USD"},
    "SMSN": {"name": "Samsung", "sector": "Technology", "region": "EU", "currency": "GBP"},
    "SMT": {"name": "SCOTTISH MORTGAGE INVESTMENT TR", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "SMWH": {"name": "WH Smith", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "SN.": {"name": "Smith & Nephew PLC", "sector": "Healthcare", "region": "EU", "currency": "GBP"},
    "SNAP": {"name": "Snap Inc", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "SNOW": {"name": "Snowflake Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "SOFI": {"name": "SoFi Technologies, Inc.", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "SOI": {"name": "Soitec", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "SOUN": {"name": "SOUNDHOUND AI CL A ORD", "sector": "Technology", "region": "US", "currency": "USD"},
    "SPCE": {"name": "Virgin Galactic Holdings Inc", "sector": "Industrials", "region": "US", "currency": "USD"},
    "SPCX": {"name": "SpaceX", "sector": "Industrials", "region": "US", "currency": "USD"},
    "SPIE": {"name": "Spie", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SPX": {"name": "Spirax Sarco", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "SRCGB": {"name": "SigmaRoc PLC", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "SRE.L": {"name": "Sirius Real Estate Limited", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "SRT": {"name": "SARTORIUS AG O.N.", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "SSE": {"name": "SSE", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "SSPG": {"name": "SSP Group", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "STAN": {"name": "Standard Chartered - GBP", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "STJ": {"name": "St. James's Place PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "STMPA": {"name": "STMicroelectronics", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "STX": {"name": "Seagate", "sector": "Technology", "region": "US", "currency": "USD"},
    "STZ": {"name": "Constellation Brands", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "SUP": {"name": "Schneider", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SVEL": {"name": "Kendrion", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SWFR": {"name": "Sodexo", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "SY1": {"name": "Symrise", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "SYNT": {"name": "Synthomer", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "SZG": {"name": "Salzgitter", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "SZU": {"name": "Suedzucker", "sector": "Consumer Defensive", "region": "EU", "currency": "EUR"},
    "TASK": {"name": "TaskUs Inc.", "sector": "Technology", "region": "US", "currency": "USD"},
    "TEGDE": {"name": "TAG Immobilien", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "TEM": {"name": "Tempus AI Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "TEP": {"name": "Telecom Plus", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "TFIP": {"name": "TF1", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "TFW": {"name": "FW Thorpe PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "TGA": {"name": "Thungela Resources Limited", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "TKA": {"name": "Thyssenkrupp", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "TLRY": {"name": "Tilray Inc", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "TLW": {"name": "Tullow", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "TMV": {"name": "TeamViewer AG", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "TOM2": {"name": "TomTom", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "TRIG": {"name": "Renewables Infrastructure Group", "sector": "Utilities", "region": "EU", "currency": "GBP"},
    "TRI_EUR": {"name": "Trigano", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "TRNGBP": {"name": "Trainline Plc", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "TSCOL": {"name": "Tesco", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "TSLA": {"name": "Tesla Inc", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "TSM": {"name": "Taiwan Semiconductor Manufacturing Co Ltd - ADR", "sector": "Technology", "region": "US", "currency": "USD"},
    "TTD": {"name": "The Trade Desk, Inc.", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "TTEF": {"name": "TotalEnergies SE", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "TTWO": {"name": "Take-Two", "sector": "Communication Services", "region": "US", "currency": "USD"},
    "TUI1": {"name": "TUI - EUR", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "TW.": {"name": "Taylor Wimpey", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "TWKNC": {"name": "TKH Group", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "UAA": {"name": "Under Armour", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "UBER": {"name": "Uber Technologies Inc", "sector": "Technology", "region": "US", "currency": "USD"},
    "UBIP": {"name": "Ubisoft Entertainment", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "ULVR": {"name": "Unilever - GBP", "sector": "Consumer Defensive", "region": "EU", "currency": "GBP"},
    "UMG": {"name": "Universal Music Group N.V.", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "UN0": {"name": "Uniper", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "UNH": {"name": "Unitedhealth", "sector": "Healthcare", "region": "US", "currency": "USD"},
    "UPS": {"name": "United Parcel", "sector": "Industrials", "region": "US", "currency": "USD"},
    "UTDI": {"name": "United Internet", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "UTG": {"name": "UNITE Group PLC", "sector": "Real Estate", "region": "EU", "currency": "GBP"},
    "V": {"name": "Visa Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "VBKDE": {"name": "Verbio", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "VCT": {"name": "Vicat", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "VCTL": {"name": "Victrex", "sector": "Basic Materials", "region": "EU", "currency": "GBP"},
    "VICR": {"name": "Vicor Corp", "sector": "Technology", "region": "US", "currency": "USD"},
    "VIE": {"name": "Veolia", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "VIRP": {"name": "Virbac SA", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "VITL": {"name": "Vital Farms Inc", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "VIVP": {"name": "Vivendi", "sector": "Communication Services", "region": "EU", "currency": "EUR"},
    "VK": {"name": "Vallourec", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "VLA": {"name": "Valneva SE", "sector": "Healthcare", "region": "EU", "currency": "EUR"},
    "VLO": {"name": "Valero", "sector": "Energy", "region": "US", "currency": "USD"},
    "VLTSA": {"name": "Voltalia SA", "sector": "Utilities", "region": "EU", "currency": "EUR"},
    "VNA": {"name": "Vonovia SE", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "VODL": {"name": "Vodafone Group PLC", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "VOPA": {"name": "Koninklijke Vopak", "sector": "Energy", "region": "EU", "currency": "EUR"},
    "VOW3": {"name": "Volkswagen AG (Pfd)", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "VRT": {"name": "Vertiv Holdings Co", "sector": "Industrials", "region": "US", "currency": "USD"},
    "VST": {"name": "Vistra Energy", "sector": "Utilities", "region": "US", "currency": "USD"},
    "WAF": {"name": "Siltronic", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "WCH": {"name": "Wacker Chemie", "sector": "Basic Materials", "region": "EU", "currency": "EUR"},
    "WDC": {"name": "Western Digital", "sector": "Technology", "region": "US", "currency": "USD"},
    "WEHA": {"name": "Wereldhave", "sector": "Real Estate", "region": "EU", "currency": "EUR"},
    "WEIR": {"name": "The Weir Group PLC", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "WEN": {"name": "The Wendy's", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "WISEA": {"name": "Wise Group PLC", "sector": "Financial Services", "region": "EU", "currency": "GBP"},
    "WIZZ": {"name": "Wizz Air", "sector": "Industrials", "region": "EU", "currency": "GBP"},
    "WLN": {"name": "Worldline", "sector": "Technology", "region": "EU", "currency": "EUR"},
    "WLSNC": {"name": "Wolters Kluwer", "sector": "Industrials", "region": "EU", "currency": "EUR"},
    "WMT": {"name": "Wal-Mart Stores Inc", "sector": "Consumer Defensive", "region": "US", "currency": "USD"},
    "WPP": {"name": "WPP PLC", "sector": "Communication Services", "region": "EU", "currency": "GBP"},
    "WTB": {"name": "Whitbread", "sector": "Consumer Cyclical", "region": "EU", "currency": "GBP"},
    "WU": {"name": "Western Union", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "WULF": {"name": "TeraWulf Inc", "sector": "Financial Services", "region": "US", "currency": "USD"},
    "XOM": {"name": "Exxon Mobil Corp", "sector": "Energy", "region": "US", "currency": "USD"},
    "XPEV": {"name": "XPeng Inc - ADR", "sector": "Consumer Cyclical", "region": "US", "currency": "USD"},
    "YCA": {"name": "Yellow Cake PLC", "sector": "Energy", "region": "EU", "currency": "GBP"},
    "ZAL": {"name": "Zalando", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "ZIL2": {"name": "Elringklinger", "sector": "Consumer Cyclical", "region": "EU", "currency": "EUR"},
    "ZS": {"name": "Zscaler", "sector": "Technology", "region": "US", "currency": "USD"},
    "ZTS": {"name": "Zoetis", "sector": "Healthcare", "region": "US", "currency": "USD"},
}
